#!/usr/bin/env python
# vim:set ft=python et sw=4 encoding=utf-8:
#
# © 2009 Philipp Kern <philipp.kern@itomig.de>
#
# Licensed under the EUPL, Version 1.0 or – as soon they
# will be approved by the European Commission - subsequent
# versions of the EUPL (the "Licence");
# you may not use this work except in compliance with the
# Licence.
# You may obtain a copy of the Licence at:
# 
# http://ec.europa.eu/idabc/eupl
# 
# Unless required by applicable law or agreed to in
# writing, software distributed under the Licence is
# distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied.
# See the Licence for the specific language governing
# permissions and limitations under the Licence.

from itomig.vbox import VBoxRegistry, Config, OptionParser
import sys

def main(argv):
    # Parse command-line parameters.
    usage = 'usage: %prog [options] vm-identifier'
    parser = OptionParser(usage)
    parser.add_option('-o', '--output-file', dest='output_file',
                      metavar='FILE', help='the output file to write to')
    parser.add_option('--vbox-home', dest='vbox_home',
                      metavar='DIR', help='VirtualBox home directory')
    parser.add_option('-s', '--data-disk-size', dest='data_disk_size',
                      metavar='SIZE', help='size of data disk in MB')
    (options, args) = parser.parse_args(argv)
    if len(args) != 2:
        parser.error('incorrect number of arguments')
    vm_identifier = args[1]
    config = Config(options)
    registry = VBoxRegistry(options.vbox_home)
    registry.dump_vm_config(vm_identifier, output_file=options.output_file,
                            data_disk_size=options.data_disk_size)

if __name__ == '__main__':
    main(sys.argv)

