.TH VBOX-SYNC-ADMIN "1" "March 2010" "vbox-sync 0.3" "User Commands"
.SH NAME
vbox-sync-admin \- modifies a vbox-sync image
.SH SYNOPSIS
.B vbox-sync-admin
.SH DESCRIPTION
.B vbox-sync-admin
is a graphical tool that starts a virtual machine, packaged using vbox-sync, with the system partition writeable. After the user has finished modifying the system image, it will be copied to the current working directory. Also, a Debian package will be created, refering to the newly created version of the virtual system.
.SH "SEE ALSO"
.BR vbox-invoke (1), vbox-dispose (8), vbox-sync (8)
.SH AUTHOR
Joachim Breitner <joachim.breitner@itomig.de>.
